version: '3.9'

services:
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs

  backend:
    build: ../
    ports:
      - "8000:8000"
    environment:
      - IPFS_API=http://ipfs:5001
    depends_on:
      - ipfs

volumes:
  ipfs_staging:
  ipfs_data:
